typography_spectrum: 0.6493188245221972
color:
  brandStrength: 0.07270365301519632
  lightness: 0.8311137584969401
  saturation: 0.7613621926866472
  rhythmicContrast: 0.4149215053766966
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
opengraph:
  appId: aerobatica@gmail.com
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/7feb8855-a1af-49fa-b17c-932f57623cee.jpg
layout_spectrum: 0.22887511947192252
author:
  name: José Luís Nunes Martins
  email: aerobatica@gmail.com
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9731dfaa-342e-43bc-9124-bdd3db2a7bdc.jpg
name: José Luís Nunes Martins
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/f33c64b4-ffce-4b2b-accb-52bb1b8cfc41.jpg
